services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "${OLLAMA_PORT}:${OLLAMA_PORT}"
    volumes:
      - ollama:/root/.ollama
      - ./ollama-entrypoint.sh:/entrypoint.sh
    entrypoint: ["/entrypoint.sh"]
    environment:
      - OLLAMA_HOST=0.0.0.0
      - "OLLAMA_PORT=${OLLAMA_PORT}"
    restart: unless-stopped

  # life-manager:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: life_manager_app
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   environment:
  #     DATABASE_URL: ${DATABASE_URL}
  #     RUST_LOG: debug
  #     APP_PORT: ${APP_PORT}
  #   ports:
  #     - "${APP_PORT}:${APP_PORT}"
  #   restart: on-failure

  tesseract:
    image: hertzg/tesseract-server:latest
    container_name: tesseract
    ports:
      - "${TESSERACT_PORT}:${TESSERACT_PORT}"
    environment:
      - TESSERACT_LANGUAGE=eng
    restart: unless-stopped

volumes:
  ollama:
